CREATE TABLE BANK.T_MENU_PRIVILEGE (
  PKID	VARCHAR(40)	NOT NULL,
  ROLE_ID	VARCHAR(40),
  MENU_ID	VARCHAR(40),
  PRIVILEGE_ID	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_MENU_PRIVILEGE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_MENU_PRIVILEGE
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BANK.T_ORGAN
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_PRIVILEGE (
  PRIVILEGE_ID	VARCHAR(40)	NOT NULL,
  PRIVILEGE_TYPE	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_PRIVILEGE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_PRIVILEGE
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_ROLE (
  ROLE_ID	VARCHAR(40)	NOT NULL,
  ROLE_DESCR	VARCHAR(200)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_ROLE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_ROLE
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_SYS_MENU (
  MENU_ID	INTEGER	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  MENU_DESCR	VARCHAR(200),
  MENU_URL	VARCHAR(400),
  MENU_PID	INTEGER,
  MENU_NAME	VARCHAR(40),
  ISLEAF	CHARACTER(10),
  ISSYSTEM	CHARACTER(10),
  SEQ	INTEGER
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_SYS_MENU
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_SYS_MENU
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_USER (
  USER_ID	VARCHAR(40)	NOT NULL,
  USER_NAME	VARCHAR(40),
  PASSWORD	VARCHAR(40),
  SEX	INTEGER,
  BIRTHDAY	DATE,
  ADDRESS	VARCHAR(100),
  ORGAN_ID	VARCHAR(40),
  USER_CNNAME	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_USER
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_USER ( 
	USER_ID IS '用户ID',
	USER_NAME IS '用户名',
	USER_CNNAME IS '员工姓名' );

COMMIT;

RUNSTATS ON TABLE BANK.T_USER
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_USER_ROLE (
  USER_ID	VARCHAR(40)	NOT NULL,
  ROLE_ID	VARCHAR(40)	NOT NULL
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_USER_ROLE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_USER_ROLE
	ALLOW WRITE ACCESS;
	
CREATE TABLE BANK.T_ORGAN (
  ORGAN_ID	VARCHAR(40)	NOT NULL,
  ORGAN_NAME	VARCHAR(40),
  ORGAN_PID	VARCHAR(40),
  ORGAN_SHORT	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_ORGAN
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_ORGAN
	ALLOW WRITE ACCESS;
