CREATE TABLE BANK.T_MENU_PRIVILEGE (
  PKID	VARCHAR(40)	NOT NULL,
  ROLE_ID	VARCHAR(40),
  MENU_ID	VARCHAR(40),
  PRIVILEGE_ID	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_MENU_PRIVILEGE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_MENU_PRIVILEGE
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BANK.T_ORGAN
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_PRIVILEGE (
  PRIVILEGE_ID	VARCHAR(40)	NOT NULL,
  PRIVILEGE_TYPE	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_PRIVILEGE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_PRIVILEGE
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_ROLE (
  ROLE_ID	VARCHAR(40)	NOT NULL,
  ROLE_DESCR	VARCHAR(200),
  ROLE_NAME	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_ROLE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_ROLE
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_SYS_MENU (
  MENU_ID	INTEGER	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  MENU_DESCR	VARCHAR(200),
  MENU_URL	VARCHAR(400),
  MENU_PID	INTEGER,
  MENU_NAME	VARCHAR(40),
  ISLEAF	CHARACTER(10),
  ISSYSTEM	CHARACTER(10),
  SEQ	INTEGER
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_SYS_MENU
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_SYS_MENU
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_USER (
  USER_ID	VARCHAR(40)	NOT NULL,
  USER_NAME	VARCHAR(40),
  PASSWORD	VARCHAR(40),
  SEX	INTEGER,
  BIRTHDAY	DATE,
  ADDRESS	VARCHAR(100),
  ORGAN_ID	VARCHAR(40),
  USER_CNNAME	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_USER
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_USER ( 
	USER_ID IS '用户ID',
	USER_NAME IS '用户名',
	USER_CNNAME IS '员工姓名' );

COMMIT;

RUNSTATS ON TABLE BANK.T_USER
	ALLOW WRITE ACCESS;

CREATE TABLE BANK.T_USER_ROLE (
  USER_ID	VARCHAR(40)	NOT NULL,
  ROLE_ID	VARCHAR(40)	NOT NULL
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_USER_ROLE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_USER_ROLE
	ALLOW WRITE ACCESS;
	
CREATE TABLE BANK.T_ORGAN (
  ORGAN_ID	VARCHAR(40)	NOT NULL,
  ORGAN_NAME	VARCHAR(40),
  ORGAN_PID	VARCHAR(40),
  ORGAN_SHORT	VARCHAR(40)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_ORGAN
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMIT;

RUNSTATS ON TABLE BANK.T_ORGAN
	ALLOW WRITE ACCESS;
	
CREATE TABLE BANK.T_COOPERATION (
  COOPERATIONID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COOPERATIONNAME	VARCHAR(80),
  ORGACODE	VARCHAR(10),
  TAXCODE	VARCHAR(35),
  REGISTERADDRESS	VARCHAR(80),
  MAILADDRESS	VARCHAR(80),
  REGISTERDATE	DATE,
  REGISTERCAPITAL	VARCHAR(30),
  REALCAPITAL	VARCHAR(30),
  LEGALPERSON	VARCHAR(50),
  IDNUM	VARCHAR(20),
  PHONE	VARCHAR(15),
  MEMBERS	INTEGER,
  BUSINESSCOPE	VARCHAR(100),
  BUSINESSAREA	INTEGER,
  FARMERS	INTEGER,
  CONNECTIONBASE	VARCHAR(10),
  RECORDER	VARCHAR(10),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COOPERATION
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COOPERATION ( 
	COOPERATIONID IS '农民专业经济合作组织表主键',
	COOPERATIONNAME IS '农民专业经济合作组织名称',
	ORGACODE IS '组织机构编号',
	TAXCODE IS '税务登记号',
	REGISTERADDRESS IS '注册地址',
	MAILADDRESS IS '通信地址',
	REGISTERDATE IS '注册时间',
	REGISTERCAPITAL IS '注册资本',
	REALCAPITAL IS '实收资本',
	LEGALPERSON IS '法定代表人',
	IDNUM IS '身份证号',
	PHONE IS '联系电话',
	MEMBERS IS '社员人数',
	BUSINESSCOPE IS '经营范围',
	BUSINESSAREA IS '经营场地面积',
	FARMERS IS '带动农户(户)',
	CONNECTIONBASE IS '连接基地',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COOPERATION
	ALLOW WRITE ACCESS;
CREATE TABLE BANK.T_COOPERATION_DEBT (
  DEBTID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COOPERATIONNAME	VARCHAR(10),
  ORGANCODE	VARCHAR(10),
  CASHCAPITAL	VARCHAR(20),
  SHORTINVEST	VARCHAR(20),
  RECEIVABLES	VARCHAR(20),
  PREPAYMENT	VARCHAR(20),
  INVENTORY	VARCHAR(20),
  FLOATASSET	VARCHAR(10),
  FLOATASSETALL	VARCHAR(20),
  FIXEDASSET	VARCHAR(20),
  DEPRECICATION	VARCHAR(20),
  NETVALUE	VARCHAR(20),
  BUILDINGPROJECT	VARCHAR(20),
  FIXEDASSETALL	VARCHAR(20),
  INVISIBLEASSET	VARCHAR(20),
  ASSETALL	VARCHAR(20),
  SHORTLOAN	VARCHAR(20),
  BANKLOAN	VARCHAR(20),
  ACCOUNTSPAYABLE	VARCHAR(20),
  DEPOSITRECEIVED	VARCHAR(20),
  UNPAIDTAX	VARCHAR(20),
  FLOATDEBT	VARCHAR(20),
  FLOATDEBTALL	VARCHAR(20),
  LONGDEBTALL	VARCHAR(20),
  REGISTERCAPITAL	VARCHAR(20),
  REALCAPITAL	VARCHAR(20),
  CAPITALRESERVE	VARCHAR(20),
  SURPLUSRESERVE	VARCHAR(20),
  UNALLOTPROFIT	VARCHAR(20),
  TOTALEQUITY	VARCHAR(20),
  TOTALEQUITY1	VARCHAR(20),
  HANDINGCOST	VARCHAR(20),
  FINANCIALCOST	VARCHAR(20),
  INTERESTEXPENSE	VARCHAR(20),
  BUSINESSPROFIT	VARCHAR(20),
  INVESTINCOME	VARCHAR(20),
  SUBSIDYINCOME	VARCHAR(20),
  UNBUSINESSINCOME	VARCHAR(20),
  UNBUSINESSEXPENSE	VARCHAR(20),
  PROFITLOSS	VARCHAR(20),
  TOTALPROFIT	VARCHAR(20),
  PAYABLEINCOMETAX	VARCHAR(20),
  PAYABLEADDEDTAX	VARCHAR(20),
  PAIDADDEDTAX	VARCHAR(20),
  NETPROFIT	VARCHAR(20),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COOPERATION_DEBT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COOPERATION_DEBT ( 
	DEBTID IS '农村经济合作组织资产负债表主键',
	COOPERATIONNAME IS '农村经济合作组织名称',
	ORGANCODE IS '组织机构编码',
	CASHCAPITAL IS '货币资金',
	SHORTINVEST IS '短期投资',
	RECEIVABLES IS '应收账款',
	PREPAYMENT IS '预付账款',
	INVENTORY IS '存货',
	FLOATASSET IS '其他流动资产',
	FLOATASSETALL IS '流动资产合计',
	FIXEDASSET IS '固定资产原价',
	DEPRECICATION IS '其中折旧',
	NETVALUE IS '固定资产净值',
	BUILDINGPROJECT IS '在建项目',
	FIXEDASSETALL IS '固定资产合计',
	INVISIBLEASSET IS '无形及递延资产合计',
	ASSETALL IS '资产合计',
	SHORTLOAN IS '短期借款',
	BANKLOAN IS '银行借款',
	ACCOUNTSPAYABLE IS '应付账款',
	DEPOSITRECEIVED IS '预收账款',
	UNPAIDTAX IS '未缴税金',
	FLOATDEBT IS '其他流动负债',
	FLOATDEBTALL IS '流动负债合计',
	LONGDEBTALL IS '长期负债合计',
	REGISTERCAPITAL IS '注册资本',
	REALCAPITAL IS '实收资本',
	CAPITALRESERVE IS '资本公积',
	SURPLUSRESERVE IS '盈余公积',
	UNALLOTPROFIT IS '未分配利润',
	TOTALEQUITY IS '所有者权益合计',
	TOTALEQUITY1 IS '负债和所有者权益合计',
	HANDINGCOST IS '管理费用',
	FINANCIALCOST IS '财务费用',
	INTERESTEXPENSE IS '其中利息支出',
	BUSINESSPROFIT IS '营业利润',
	INVESTINCOME IS '投资收益',
	SUBSIDYINCOME IS '国家补贴收入',
	UNBUSINESSINCOME IS '营业外收入',
	UNBUSINESSEXPENSE IS '营业外支出',
	PROFITLOSS IS '以前年度损益调整',
	TOTALPROFIT IS '利润总和',
	PAYABLEINCOMETAX IS '应交所得税',
	PAYABLEADDEDTAX IS '应交增值税',
	PAIDADDEDTAX IS '实交增值税',
	NETPROFIT IS '利润净额',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COOPERATION_DEBT
	ALLOW WRITE ACCESS;



