CREATE TABLE BANK.T_COMAPNY_FINANCE (
  FINANCEID	BIGINT,
  REPORTORGAN	VARCHAR(80),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  TAXCODE	VARCHAR(20),
  OCCUR_YEAR	INTEGER,
  STAGETYPE	VARCHAR(20),
  RECEIVEDEBT_AMOUNT	VARCHAR(20),
  RECEIVEDEBT_TYPE	INTEGER,
  PAYABLE_AMOUNT	VARCHAR(20),
  PAYABLE_TYPE	INTEGER,
  INVENTORYNAME	VARCHAR(40),
  INVENTORYCOST	VARCHAR(20),
  INVENTORYTIME	VARCHAR(10),
  INVENTORYREASON	VARCHAR(100),
  INVENTORYVALUE	VARCHAR(20),
  RECORDER	VARCHAR(10),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMAPNY_FINANCE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMAPNY_FINANCE ( 
	FINANCEID IS '企业经营财务补充信息表',
	REPORTORGAN IS '数据报送机构',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	TAXCODE IS '税务识别码',
	OCCUR_YEAR IS '数据发生年份',
	STAGETYPE IS '其别类型',
	RECEIVEDEBT_AMOUNT IS '应收账款金额',
	RECEIVEDEBT_TYPE IS '应收账款类型',
	PAYABLE_AMOUNT IS '应付账款金额',
	PAYABLE_TYPE IS '应付账款类型',
	INVENTORYNAME IS '存货名称',
	INVENTORYCOST IS '存货金额',
	INVENTORYTIME IS '存货时间',
	INVENTORYREASON IS '存货原因',
	INVENTORYVALUE IS '存货可变现净值',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMAPNY_FINANCE
	ALLOW WRITE ACCESS;

