CREATE TABLE BANK.T_COMPANY_PERMIT (
  PERMITID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  DATATIME	VARCHAR(10),
  DATAUNIT	VARCHAR(50),
  PERMITTIME	DATE,
  PERMITSCOPE	VARCHAR(50),
  VALIDENDTIME	DATE,
  REMARK	VARCHAR(1000),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_PERMIT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_PERMIT IS '企业许可信息';

COMMENT ON BANK.T_COMPANY_PERMIT ( 
	PERMITID IS '企业许可信息表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	DATATIME IS '数据时间',
	DATAUNIT IS '数据单位',
	PERMITTIME IS '许可时间',
	PERMITSCOPE IS '许可范围',
	VALIDENDTIME IS '有效截止日期止',
	REMARK IS '备注',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_PERMIT
	ALLOW WRITE ACCESS;

