CREATE TABLE BANK.T_COMPANY_CAPITAL (
  CAPITALID	INTEGER	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYID	INTEGER,
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  REGISTERCAPITAL	INTEGER,
  CURRENCY	VARCHAR(6),
  REALCAPITAL	INTEGER,
  CAPITALCHKNUM	VARCHAR(20),
  INVESTOR	VARCHAR(80),
  BUSINESSCODE	VARCHAR(20),
  IDTYPE	VARCHAR(5),
  IDNUMBER	VARCHAR(18),
  INVESTAMOUNT	VARCHAR(8),
  INVESTSTYLE	VARCHAR(100),
  INVESTDATE	DATE,
  EVALUATEORGAN	VARCHAR(80),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_CAPITAL
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_CAPITAL ( 
	CAPITALID IS '资本表主键',
	COMPANYID IS '企业表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构代码',
	CREDITCODE IS '机构信用代码',
	REGISTERCAPITAL IS '注册资本金额',
	CURRENCY IS '币种',
	REALCAPITAL IS '实缴资本金额',
	CAPITALCHKNUM IS '最近一次验资报告文号',
	INVESTOR IS '出资人名称',
	BUSINESSCODE IS '工商等级注册号',
	IDTYPE IS '证件类型',
	IDNUMBER IS '证件号码',
	INVESTAMOUNT IS '出资金额',
	INVESTSTYLE IS '出资方式',
	INVESTDATE IS '出资日期',
	EVALUATEORGAN IS '资产评估机构',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_CAPITAL
	ALLOW WRITE ACCESS;

