CREATE TABLE BANK.T_COMPANY_EMPLOYEE (
  EMPLOYEEID	INTEGER	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  NAME	VARCHAR(20),
  SEX	INTEGER,
  BIRTHDAY	DATE,
  CATEGORY	INTEGER,
  IDTYPE	VARCHAR(10),
  IDNUMBER	VARCHAR(18),
  POST	INTEGER,
  POSTTIME	DATE,
  DEGREE	INTEGER,
  STOCKAMOUNT	INTEGER,
  SKILL	VARCHAR(100),
  SKILLWINTIME	DATE,
  PARTTIMEJOB	VARCHAR(10),
  WORKRESUME	VARCHAR(1000),
  AWARD	VARCHAR(1000),
  OTHERCOMPANYNAME	VARCHAR(80),
  OTHERREGISTERCODE	VARCHAR(20),
  OTHERPOST	VARCHAR(20),
  OTHERINVESTAMOUNT	INTEGER,
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_EMPLOYEE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_EMPLOYEE ( 
	EMPLOYEEID IS '企业高管表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构代码',
	CREDITCODE IS '机构信用代码',
	NAME IS '高管人员姓名',
	SEX IS '高管人员性别',
	BIRTHDAY IS '出生日期',
	CATEGORY IS '高管人员类别',
	IDTYPE IS '证件类型',
	IDNUMBER IS '证件号码',
	POST IS '职务',
	POSTTIME IS '担任本职时间',
	DEGREE IS '最高学历',
	STOCKAMOUNT IS '持有公司股份',
	SKILL IS '技能资格',
	SKILLWINTIME IS '技能资格取得时间',
	PARTTIMEJOB IS '社会兼职',
	WORKRESUME IS '工作简历',
	AWARD IS '个人受奖励情况',
	OTHERCOMPANYNAME IS '在其他企业投资或者任职的企业名称',
	OTHERREGISTERCODE IS '在其他企业投资或任职的企业工商等级注册号',
	OTHERPOST IS '在其投资或任职的其他企业所担任的职务',
	OTHERINVESTAMOUNT IS '在其投资或任职的其他企业的投资额',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_EMPLOYEE
	ALLOW WRITE ACCESS;

