CREATE TABLE BANK.T_COMPANY_CHANGE (
  CHANGEID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  DATATIME	VARCHAR(20),
  DATAUNIT	VARCHAR(20),
  CHANGETIME	DATE,
  CHANGEITEMS	VARCHAR(20),
  BEFORECHANGE	VARCHAR(1000),
  AFTERCHANGE	VARCHAR(1000),
  REMARK	VARCHAR(1000),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_CHANGE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_CHANGE IS '企业变更信息';

COMMENT ON BANK.T_COMPANY_CHANGE ( 
	CHANGEID IS '企业变更信息表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	DATATIME IS '数据时间',
	DATAUNIT IS '数据单位',
	CHANGETIME IS '变更时间',
	CHANGEITEMS IS '变更事项',
	BEFORECHANGE IS '变更前',
	AFTERCHANGE IS '变更后',
	REMARK IS '备注',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_CHANGE
	ALLOW WRITE ACCESS;

