CREATE TABLE BANK.T_COMPANY_GRADE (
  GRADEID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  CREDITLEVEL	VARCHAR(10),
  GRADETIME	DATE,
  GRADEORGAN	VARCHAR(20),
  GRADEPROOF	INTEGER,
  GRADEVALIDTIME	VARCHAR(10),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_GRADE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_GRADE ( 
	GRADEID IS '企业外部评级信息表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构',
	CREDITCODE IS '机构信用编码',
	CREDITLEVEL IS '信用等级',
	GRADETIME IS '评级时间',
	GRADEORGAN IS '评级机构',
	GRADEPROOF IS '评级证书号',
	GRADEVALIDTIME IS '评价有效期',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_GRADE
	ALLOW WRITE ACCESS;

