CREATE TABLE BANK.T_COMPANY_PUBLICFOUND (
  PUBLICFOUNDID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  DATATIME	VARCHAR(10),
  PAYMENTBEGINTIME	DATE,
  PAYMENTENDTIME	DATE,
  PAYMENTGATHERTIME	DATE,
  GATHERSTATUS	INTEGER,
  PAYMENTNUM	INTEGER,
  PAYMENTAMOUNT	INTEGER,
  PAYMENTRATIO	INTEGER,
  ARREARNUM	DATE,
  ARREARAMOUNT	INTEGER,
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_PUBLICFOUND
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_PUBLICFOUND ( 
	COMPANYNAME IS '企业名称',
	PAYMENTBEGINTIME IS '初缴时间',
	PAYMENTENDTIME IS '缴至时间',
	PAYMENTGATHERTIME IS '最近一次汇缴时间',
	GATHERSTATUS IS '单位当月汇缴状态',
	PAYMENTNUM IS '缴存人数',
	PAYMENTAMOUNT IS '缴存金额',
	PAYMENTRATIO IS '缴存比例',
	ARREARNUM IS '欠缴日期',
	ARREARAMOUNT IS '欠缴金额',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_PUBLICFOUND
	ALLOW WRITE ACCESS;

