CREATE TABLE BANK.T_COMPANY_COMMEND (
  COMMENDID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  COMMENDDEPT	INTEGER,
  COMMENDDETAIL	VARCHAR(100),
  COMMANDDECLARE	VARCHAR(100),
  COMMANDDATE	DATE,
  QUALIFICATION	VARCHAR(100),
  REMARK	VARCHAR(1000),
  RECORDER	VARCHAR(10),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_COMMEND
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_COMMEND ( 
	COMMENDID IS '企业受表彰情况',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	COMMENDDEPT IS '表彰部门',
	COMMENDDETAIL IS '表彰内容',
	COMMANDDECLARE IS '表彰说明',
	COMMANDDATE IS '表彰时间',
	QUALIFICATION IS '国际认证/特殊行业资质',
	REMARK IS '备注',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_COMMEND
	ALLOW WRITE ACCESS;

