CREATE TABLE BANK.T_COMPANY_EA (
  EAID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(20),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  EATIME	DATE,
  EALEVEL	VARCHAR(20),
  EAORGAN	VARCHAR(20),
  EAVALIDTIME	VARCHAR(20),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_EA
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_EA IS '企业环评信息';

COMMENT ON BANK.T_COMPANY_EA ( 
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	EATIME IS '环评时间',
	EALEVEL IS '环评等级',
	EAORGAN IS '环评机构',
	EAVALIDTIME IS '环评有效期',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_EA
	ALLOW WRITE ACCESS;

