CREATE TABLE BANK.T_COMPANY_AFFIRM (
  AFFIRMID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  DATATIME	VARCHAR(20),
  DATAUNIT	VARCHAR(20),
  AFFIRMTIME	DATE,
  AFFIRMNAME	VARCHAR(50),
  AFFIRMUNIT	VARCHAR(50),
  VALIDENDTIME	DATE,
  REMARK	VARCHAR(1000),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_AFFIRM
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_AFFIRM IS '企业认定认证信息';

COMMENT ON BANK.T_COMPANY_AFFIRM ( 
	AFFIRMID IS '企业认证认定信息',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	DATATIME IS '数据时间',
	DATAUNIT IS '数据单位',
	AFFIRMTIME IS '认证/认定时间',
	AFFIRMNAME IS '认证/认定名称',
	AFFIRMUNIT IS '认证/认定单位',
	VALIDENDTIME IS '有效截止日期',
	REMARK IS '备注',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_AFFIRM
	ALLOW WRITE ACCESS;

