CREATE TABLE BANK.T_COMPANY_PUNISH (
  PUNISHID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(20),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  PUNISHTYPE	INTEGER,
  DATATIME	DATE,
  PUNISHORGAN	VARCHAR(80),
  PUNISHDETAIL	VARCHAR(1000),
  INVOLVEAMOUNT	INTEGER,
  PUNISHAMOUNT	INTEGER,
  CURRENCY	VARCHAR(10),
  PUNISHDECIDE	VARCHAR(1000),
  ISREVIEW	INTEGER,
  REVIEWORGAN	VARCHAR(100),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_PUNISH
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_PUNISH IS '行政处罚或违规信息';

COMMENT ON BANK.T_COMPANY_PUNISH ( 
	PUNISHID IS '企业处罚或违规信息表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	PUNISHTYPE IS '违法或违规行为类别',
	DATATIME IS '数据时间',
	PUNISHORGAN IS '裁定违规或处罚机构',
	PUNISHDETAIL IS '违法或违规行为描述',
	INVOLVEAMOUNT IS '涉及金额',
	PUNISHAMOUNT IS '处罚金额',
	CURRENCY IS '币种',
	PUNISHDECIDE IS '处罚决定',
	ISREVIEW IS '是否行政复议',
	REVIEWORGAN IS '行政复议受理机关',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_PUNISH
	ALLOW WRITE ACCESS;

