CREATE TABLE BANK.T_COMPANY_WARRANT (
  WARRANTID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  OCCURTIME	DATE,
  UNIT	VARCHAR(20),
  OWNERSHIP	VARCHAR(50),
  REGISTERDETAIL	VARCHAR(50),
  REMARK	VARCHAR(100),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_WARRANT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_WARRANT IS '企业权证信息';

COMMENT ON BANK.T_COMPANY_WARRANT ( 
	WARRANTID IS '企业权证信息主表',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	OCCURTIME IS '数据时间',
	UNIT IS '数据单位',
	OWNERSHIP IS '土地/房产权属',
	REGISTERDETAIL IS '出让金缴纳情况/办理房屋登记情况',
	REMARK IS '备注',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_WARRANT
	ALLOW WRITE ACCESS;

