CREATE TABLE BANK.T_COMPANY_PAYMENT (
  PAYMENTID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  COSTCATEGORY	INTEGER,
  COSTTIME	DATE,
  COSTNUM	VARCHAR(10),
  COSTAMOUNT	INTEGER,
  ARREARTIME	VARCHAR(10),
  ARREARCOUNT	INTEGER,
  ARREARNUM	VARCHAR(10),
  ARREARAMOUNT	INTEGER,
  MSGPROVIDER	VARCHAR(80),
  RECORDER	VARCHAR(10),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_PAYMENT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_PAYMENT IS '企业公共事业缴费信息';

COMMENT ON BANK.T_COMPANY_PAYMENT ( 
	PAYMENTID IS '公共事业缴费信息主表',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	COSTCATEGORY IS '费用类别',
	COSTTIME IS '费用发生时间',
	COSTNUM IS '本期费用度数',
	COSTAMOUNT IS '费用金额',
	ARREARTIME IS '欠缴日期',
	ARREARCOUNT IS '欠缴次数',
	ARREARNUM IS '欠费度数',
	ARREARAMOUNT IS '欠缴金额',
	MSGPROVIDER IS '消息来源机构',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_PAYMENT
	ALLOW WRITE ACCESS;

