CREATE TABLE BANK.T_COMPANY_ACCOUNTPERMIT (
  PERMITID	BIGINT,
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  DATATIME	VARCHAR(20),
  DATAUNIT	VARCHAR(50),
  LEGALPERSON	VARCHAR(20),
  BANKNAME	VARCHAR(30),
  RATIFYNUMBER	VARCHAR(20),
  PERMITTIME	DATE,
  REMARK	VARCHAR(1000),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_ACCOUNTPERMIT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE BANK.T_COMPANY_ACCOUNTPERMIT IS '企业基本户开户信息';

COMMENT ON BANK.T_COMPANY_ACCOUNTPERMIT ( 
	PERMITID IS '企业基本存款账户开户许可信息表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	DATATIME IS '数据时间',
	DATAUNIT IS '数据单位',
	LEGALPERSON IS '法人代表',
	BANKNAME IS '开户银行',
	RATIFYNUMBER IS '开户行核准号',
	PERMITTIME IS '许可时间',
	REMARK IS '备注',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_ACCOUNTPERMIT
	ALLOW WRITE ACCESS;

