CREATE TABLE BANK.T_COMPANY_AUDIT (
  AUDITID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  DATATIME	VARCHAR(10),
  DATAUNIT	VARCHAR(20),
  AUDITTIME	DATE,
  AUDITNAME	VARCHAR(20),
  VALIDENDTIME	DATE,
  REMARK	VARCHAR(100),
  RECORDER	VARCHAR(20),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_AUDIT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_AUDIT ( 
	AUDITID IS '企业年审信息表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	DATATIME IS '数据时间',
	DATAUNIT IS '数据单位',
	AUDITTIME IS '年审时间',
	AUDITNAME IS '年审证件名称',
	VALIDENDTIME IS '有效截止日期',
	REMARK IS '备注',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_AUDIT
	ALLOW WRITE ACCESS;

