CREATE TABLE BANK.T_COMPANY_CREDIT (
  CREDITID	INTEGER,
  COMPANYNAME	VARCHAR(80),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(20),
  OCCURYEAR	VARCHAR(4),
  ISSUETYPE	INTEGER,
  PAYTYPE	INTEGER,
  GATHERINGTYPE	INTEGER,
  PURCHASENUM	INTEGER,
  PURCHASEAMOUNT	VARCHAR(10),
  REALPAY	VARCHAR(10),
  SELLNUM	INTEGER,
  SELLAMOUNT	VARCHAR(10),
  REALSELL	VARCHAR(10),
  RECORDER	VARCHAR(20),
  RECORDTIME	DATE
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_CREDIT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_CREDIT ( 
	CREDITID IS '企业信用表主键',
	COMPANYNAME IS '企业名称',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	OCCURYEAR IS '数据发生年份',
	ISSUETYPE IS '其别类型',
	PAYTYPE IS '主要采购支付方式',
	GATHERINGTYPE IS '主要销售收款方式',
	PURCHASENUM IS '采购合同数量',
	PURCHASEAMOUNT IS '采购合同金额',
	REALPAY IS '实际采购支出',
	SELLNUM IS '销售合同数量',
	SELLAMOUNT IS '销售合同金额',
	REALSELL IS '实际销售收入',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_CREDIT
	ALLOW WRITE ACCESS;

