CREATE TABLE BANK.T_COMPANY_COMPACT (
  COMPACTID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  ORGANCODE	VARCHAR(20),
  CREDITCODE	VARCHAR(10),
  OCCUR_YEAR	TIMESTAMP(4),
  STAGETYPE	INTEGER,
  BUYTYPE	INTEGER,
  SELLTYPE	INTEGER,
  BUYNUM	INTEGER,
  BUYAMOUNT	VARCHAR(30),
  REAL_BUYAMOUNT	VARCHAR(30),
  SELLNUM	INTEGER,
  SELLAMOUNT	VARCHAR(30),
  REAL_SELLAMOUNT	VARCHAR(30),
  RECORDER	VARCHAR(10),
  RECORDTIME	TIMESTAMP(12)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE BANK.T_COMPANY_COMPACT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON BANK.T_COMPANY_COMPACT ( 
	COMPACTID IS '企业购销合同情况表',
	ORGANCODE IS '组织机构编码',
	CREDITCODE IS '机构信用编码',
	OCCUR_YEAR IS '数据发生年份',
	STAGETYPE IS '其别类型',
	BUYTYPE IS '采购支付方式',
	SELLTYPE IS '销售收款方式',
	BUYNUM IS '采购合同数量',
	BUYAMOUNT IS '采购合同金额',
	REAL_BUYAMOUNT IS '实际采购支出',
	SELLNUM IS '销售合同数量',
	SELLAMOUNT IS '销售合同金额',
	REAL_SELLAMOUNT IS '实际销售收入',
	RECORDER IS '记录人',
	RECORDTIME IS '记录时间' );

COMMIT;

RUNSTATS ON TABLE BANK.T_COMPANY_COMPACT
	ALLOW WRITE ACCESS;

