package com.bank.beans.enums;

public enum CooperationDebtBZEnum {
	YEARMONTH("A"),
	COOPERATIONNAME("B"),
	ORGANCODE("C"),
	BUSINESSLICENCE("D"),
	CASHCAPITAL("E"),
	SHORTINVEST("F"),
	RECEIVABLES("G"),
	PREPAYMENT("H"),
	INVENTORY("I"),
	FLOATASSET("J"),
	FLOATASSETALL("K"),
	FIXEDASSET("L"),
	DEPRECICATION("M"),
	NETVALUE("N"),
	BUILDINGPROJECT("O"),
	FIXEDASSETALL("P"),
	INVISIBLEASSET("Q"),
	ASSETALL("R"),
	SHORTLOAN("S"),
	BANKLOAN("T"),
	ACCOUNTSPAYABLE("U"),
	DEPOSITRECEIVED("V"),
	UNPAIDTAX("W"),
	FLOATDEBT("X"),
	FLOATDEBTALL("Y"),
	LONGDEBTALL("Z"),
	REGISTERCAPITAL("AA"),
	REALCAPITAL("AB"),
	CAPITALRESERVE("AC"),
	SURPLUSRESERVE("AD"),
	UNALLOTPROFIT("AE"),
	TOTALEQUITY("AF"),
	TOTALEQUITY1("AG"),
	HANDINGCOST("AH"),
	FINANCIALCOST("AI"),
	INTERESTEXPENSE("AJ"),
	BUSINESSPROFIT("AK"),
	INVESTINCOME("AL"),
	SUBSIDYINCOME("AM"),
	UNBUSINESSINCOME("AN"),
	UNBUSINESSEXPENSE("AO"),
	PROFITLOSS("AP"),
	TOTALPROFIT("AQ"),
	PAYABLEINCOMETAX("AR"),
	PAYABLEADDEDTAX("AS"),
	PAIDADDEDTAX("AT"),
	NETPROFIT("AU");

	private String index;
	
	CooperationDebtBZEnum(String index){
		this.index = index;
	}
	public int getIndex(){
		   return ExcelMapper.getInstance().parseCode(this.index);
	}

}
